### Imports

In [1]:
import numpy as np
import time
import random
from IPython.display import Image
from IPython.core.display import HTML 
import base64, codecs

In [2]:
magic = 'ZGVmIHVuaWZvcm1fb3JkZXJfY3Jvc3NvdmVyKHAxLCBwMiwgdGVtcGxhdGUpOgoKICAgICMgY3JlYXRlICdlbXB0eScgY2hpbGQKICAgIGNoaWxkID0gbnAuemVyb3MoKGxlbihwMSksKSxkdHlwZT1pbnQpCiAgICAjIHdoZXJlIHRoZSB0ZW1wbGF0ZSBpcyB0cnVlLCB0YWtlIHZhbHVlcyBmcm9tIHAxCiAgICBjaGlsZFt0ZW1wbGF0ZV0gPSBwMVt0ZW1wbGF0ZV0KICAgIAogICAgcHJpbnQoIkNoaWxkIGF0IHN0ZXAgMSBhY2NvcmRpbmcgdG8gdGhlIGJvb2xlYW4gbWFzazogXG4iLCBjaGlsZCwgIlxuIikKICAgIHRpbWUuc2xlZXAoMSkKICAgIAogICAgIyBzdG9yZSBnZW5lcyB1c2VkIGZyb20gcDEKICAgIHVzZWRfZ2VuZXMgPSBwMVt0ZW1wbGF0ZV0KC'
love = 'vNtVPNwVTqyqPOuoTjtM2IhMKZtMaWioFOjZtbtVPNtpzIgLJyhnJ5aK2qyozImVQ0tpQVhqT9fnKA0XPxXVPNtVPZtLJExVTqyozImVTMlo20tpQVtXUEbLKDtq2IlMFOho3DtqKAyMPOzpz9gVUNkXFO0olO0nTHtMJ1jqUxtp3OiqUZto2LtqTuyVTAbnJkxPvNtVPOzo3VtnFjtqzSfqJHtnJ4tMJ51oJIlLKEyXTAbnJkxXGbXVPNtVPNtVPNwVTyzVUEbnKZtp3OiqPOcplOuoUWyLJE5VTMcoTkyMPjtL29hqTyhqJHXVPNtVPNtVPOcMvO2LJk1MFNuCFNjBtbtVPNtVPNtVPNtVPOwo250nJ51MDbXVPNtVPNtVPNwVTEiVUqbnJkyBvNtpT9jXTqyqPOuozDtpzIgo3MyXFOhMKu0VTqyozHtMaWioFOjZvO1oaEcoPOiozHtnKZtMz91ozDtqTuuqPOcplOho3DtrJ'
god = 'V0IGluIHRoZSBnZW5vbWUgb2YgdGhlIGNoaWxkLCB0aGVuIGFkZCB0aGF0CiAgICAgICAgd2hpbGUgVHJ1ZToKICAgICAgICAgICAgbmV4dF9nZW5lID0gcmVtYWluaW5nX2dlbmVzLnBvcCgwKQogICAgICAgICAgICBpZiBuZXh0X2dlbmUgbm90IGluIHVzZWRfZ2VuZXM6CiAgICAgICAgICAgICAgICBjaGlsZFtpXSA9IG5leHRfZ2VuZQogICAgICAgICAgICAgICAgcHJpbnQoIkNoaWxkIGF0IHN0ZXAgIiwgaSsxICwiOiBcbiIsIGNoaWxkLCAiXG4iKQogICAgICAgICAgICAgICAgdGltZS5zbGVlcCgxKQogICAgCiAgICAgICAgICAgICAgICBicmVhawoKICAgIHJldHVybiBjaGlsZAoKZGVmIGdldF9jcm9zc292ZXJfdGVtcGxhdGUobGVuZ3RoLCBjcm9'
destiny = 'mp292MKWspzS0MFN9VQNhZvx6PvNtVPNwVTyhnKEcLJkcrzHtqTIgpTkuqTHtq2y0nPOzLJkmMFO2LJk1MKZXVPNtVUEyoKOfLKEyVQ0toaNhrzIlo3ZbXTkyozq0nPjcYTE0rKOyCJWio2jcPvNtVPNXVPNtVPZtM2I0VUWuozEioFOcozEcL2ImVT9zVUEbMFOuoJ91oaDtV29zVTqyozImVPbtL3Wip3AiqzIlVUWuqTHXVPNtVUWuozEioI9cozEcL2ImVQ0toaNhpzShMT9gYzAbo2ywMFu0MJ1joTS0MF5mnTSjMIfjKFjtnJ50XTkyozq0nPcwpz9mp292MKWspzS0MFxfVUWypTkuL2H9EzSfp2HcPvNtVPNXVPNtVPAmMKDtqTuyp2HtnJ5xnJAyplO0olO0paIyPvNtVPO0MJ1joTS0MIglLJ5xo21snJ5xnJAyp10tCFOHpaIyPtbtVPNtpzI0qKWhVUEyoKOfLKEy'
joy = '\x72\x6f\x74\x31\x33'
trust = eval('\x6d\x61\x67\x69\x63') + eval('\x63\x6f\x64\x65\x63\x73\x2e\x64\x65\x63\x6f\x64\x65\x28\x6c\x6f\x76\x65\x2c\x20\x6a\x6f\x79\x29') + eval('\x67\x6f\x64') + eval('\x63\x6f\x64\x65\x63\x73\x2e\x64\x65\x63\x6f\x64\x65\x28\x64\x65\x73\x74\x69\x6e\x79\x2c\x20\x6a\x6f\x79\x29')
eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))

### Create random parents

In [3]:
p1 = np.array(random.sample(range(1, 11), 9))
p2 = np.array(random.sample(range(1, 11), 9))

print("These are our current parents! \n")

print("Parent 1: \n",p1,"\n")
print("Parent 2: \n",p2,"\n")

These are our current parents! 

Parent 1: 
 [ 9 10  1  8  7  4  2  6  3] 

Parent 2: 
 [ 2  7  3  4 10  8  6  9  5] 



Notice how there are duplicate entries when comparing both parents? In order to prevent the creation of invalid groups, we need to apply a special crossover operation called uniform order-based crossover. This will allow us to create children which do not share  genomes and thus only produce valid solutions!

### Create the binary template

To do this, we first need a binary crossover mask of lenght p<sub>1</sub>/p<sub>2</sub> which consists of random boolean values! The *crossover_rate* describes how many genes will be transfered over from the parent gene. Depending on the redundance of both genomes, a high *crossover_rate* may be impossible. 

In [4]:
print("Binary template for our crossover operation! \n")
template = get_crossover_template(len(p1),crossover_rate = 0.4)

print(template, "\n")

Binary template for our crossover operation! 

[ True False False False False False False  True  True] 



### Apply uniform order-based crossover operation and create a child

Moving on to the crossover operation, we start of by creating an empty child which inherits the genomes of p<sub>1</sub> in spots where the binary template is True. We now proceed to fill up all remaining genes with values of p2 that do not equal the genomes we already chose in the previous step. This process is done from left to right.

In [5]:
child = uniform_order_crossover(p1, p2, template)

Child at step 1 according to the boolean mask: 
 [9 0 0 0 0 0 0 6 3] 

Child at step  2 : 
 [9 2 0 0 0 0 0 6 3] 

Child at step  3 : 
 [9 2 7 0 0 0 0 6 3] 

Child at step  4 : 
 [9 2 7 4 0 0 0 6 3] 

Child at step  5 : 
 [ 9  2  7  4 10  0  0  6  3] 

Child at step  6 : 
 [ 9  2  7  4 10  8  0  6  3] 

Child at step  7 : 
 [ 9  2  7  4 10  8  5  6  3] 



### Summary

Now lets again take a look at all components that were involved here.

In [6]:
print("Parent 1: \n",p1,"\n")
print("Parent 2: \n",p2,"\n")
print("Binary template: \n", template, "\n")
print("Resulting child: \n", child, "\n")

Parent 1: 
 [ 9 10  1  8  7  4  2  6  3] 

Parent 2: 
 [ 2  7  3  4 10  8  6  9  5] 

Binary template: 
 [ True False False False False False False  True  True] 

Resulting child: 
 [ 9  2  7  4 10  8  5  6  3] 



### More information

Note: In the article linked below the authors create two childern instead of only one. This does not matter with regard to the overall concept, though.

https://puphaiboon-kreecha.medium.com/uniform-order-based-crossover-uox-186e137cd9bd

In [7]:
Image(url= "https://i.stack.imgur.com/5s7yX.png")