### Imports

In [1]:
import numpy as np
import time
import random

### Crossover functions

In [29]:
def uniform_order_crossover(p1, p2, template):

    # create 'empty' child
    child = np.zeros((len(p1),),dtype=int)
    # where the template is true, take values from p1
    child[template] = p1[template]
    
    print("Child at step 1 according to the boolean mask: \n", child, "\n")
    time.sleep(1)
    
    # store genes used from p1
    used_genes = p1[template]

    # get all genes from p2
    remaining_genes = p2.tolist()
    # add genes from p2 (that were not used from p1) to the empty spots of the child
    for i, value in enumerate(child):
        # if this spot is already filled, continue
        if value != 0:
            continue

        # do while:  pop(get and remove) next gene from p2 until one is found that is not yet in the genome of the child, then add that
        while True:
            next_gene = remaining_genes.pop(0)
            if next_gene not in used_genes:
                child[i] = next_gene
                print("Child at step ", i+1 ,": \n", child, "\n")
                time.sleep(1)
    
                break

    return child

def get_crossover_template(length, crossover_rate = 0.2):
    # initialize template with false values
    template = np.zeros((length,),dtype=bool)
    
    # get random indices of the amount #of genes * crossover rate
    random_indices = np.random.choice(template.shape[0], int(length*crossover_rate), replace=False)
    
    #set these indices to true
    template[random_indices] = True

    return template

### Create random parents

In [38]:
p1 = np.array(random.sample(range(1, 11), 9))
p2 = np.array(random.sample(range(1, 11), 9))

print("These are our current parents! \n")

print("Parent 1: \n",p1,"\n")
print("Parent 2: \n",p2,"\n")

These are our current parents! 

Parent 1: 
 [8 2 7 5 3 9 4 1 6] 

Parent 2: 
 [ 8  5  3  1  6  7 10  2  4] 



Notice how there are duplicate entries when comparing both parents? In order to prevent the creation of invalid groups, we need to apply a special crossover operation called uniform crossover. This will allow us to create children which do not share  genomes and thus only produce valid solutions!

### Create the binary template

To do this, we first need a binary crossover mask of lenght p<sub>1</sub>/p<sub>2</sub> which consists of random boolean values! The crossover_rate describes how many genes will be transfered over from the parent gene. Depending on the redundance of both genomes, a high crossover_rate may be impossible. 

In [41]:
print("Binary template for our crossover operation! \n")
template = get_crossover_template(len(p1),crossover_rate = 0.4)

print(template, "\n")

Binary template for our crossover operation! 

[False False False  True False False False  True  True] 



### Apply uniform crossover operation and create a child

Moving on to the crossover operation, we start of by creating an empty child which inherits the genomes of p<sub>1</sub> in spots where the binary template is True. We now proceed to fill up all remaining genes with values of p2 that do not equal the genomes we already chose in the previous step. This process is done from left to right.

In [42]:
child = uniform_order_crossover(p1, p2, template)

Child at step 1 according to the boolean mask: 
 [0 0 0 5 0 0 0 1 6] 

Child at step  1 : 
 [8 0 0 5 0 0 0 1 6] 

Child at step  2 : 
 [8 3 0 5 0 0 0 1 6] 

Child at step  3 : 
 [8 3 7 5 0 0 0 1 6] 

Child at step  5 : 
 [ 8  3  7  5 10  0  0  1  6] 

Child at step  6 : 
 [ 8  3  7  5 10  2  0  1  6] 

Child at step  7 : 
 [ 8  3  7  5 10  2  4  1  6] 



Now lets again take a look at all components that were involved here.

In [43]:
print("Parent 1: \n",p1,"\n")
print("Parent 2: \n",p2,"\n")
print("Binary template: \n", template, "\n")
print("Resulting child: \n", child, "\n")

Parent 1: 
 [8 2 7 5 3 9 4 1 6] 

Parent 2: 
 [ 8  5  3  1  6  7 10  2  4] 

Binary template: 
 [False False False  True False False False  True  True] 

Resulting child: 
 [ 8  3  7  5 10  2  4  1  6] 

